#!/usr/bin/env python3
"""
Regenerate the bundled Gujarat boundary GeoJSON used by the map overlay.

Source: Census 2011 district shapefile (data.gov.in), mirrored by
https://github.com/yashveeeeeeer/india-geodata — file:
    data/administrative/districts/census-2011/2011_Dist.shp

Outputs (TypeScript modules, inlined so the map works offline):
    src/lib/geo/gujaratDistricts.ts   district polygons (hover tooltips)
    src/lib/geo/gujaratOutline.ts     dissolved state outline
    src/lib/geo/gujaratMask.ts        world-minus-Gujarat mask (focus dim)

Usage:
    git clone --depth 1 https://github.com/yashveeeeeeer/india-geodata /tmp/india-geodata
    python3 -m venv /tmp/geotool && /tmp/geotool/bin/pip install pyshp shapely
    /tmp/geotool/bin/python scripts/make_gujarat_geojson.py
"""
from __future__ import annotations

import json
from pathlib import Path

import shapefile
from shapely.geometry import Polygon, shape
from shapely.ops import unary_union

SHAPES = Path("/tmp/india-geodata/data/administrative/districts/census-2011/2011_Dist")
OUT = Path(__file__).resolve().parents[1] / "src" / "lib" / "geo"
GUJARAT_ST_CD = 24
TOL_DISTRICTS = 0.0035
TOL_HOLE = 0.006


def rnd(gjson: dict) -> dict:
    def walk(c):
        if isinstance(c[0], (int, float)):
            return [round(c[0], 4), round(c[1], 4)]
        return [walk(x) for x in c]

    g = dict(gjson)
    g["coordinates"] = walk(gjson["coordinates"])
    return g


def main() -> None:
    r = shapefile.Reader(str(SHAPES))
    districts, polys = [], []
    for sr in r.iterShapeRecords():
        rec = sr.record
        if rec[2] != GUJARAT_ST_CD or str(rec[1]).strip().lower() != "gujarat":
            continue
        geom = shape(sr.shape.__geo_interface__)
        polys.append(geom)
        districts.append((str(rec[0]).upper(), rec[3], geom))
    if len(polys) < 20:
        raise SystemExit(f"only {len(polys)} Gujarat shapes found — wrong source file?")

    feats = [
        {
            "type": "Feature",
            "properties": {"name": n, "dt": dt},
            "geometry": rnd(g.simplify(TOL_DISTRICTS, preserve_topology=True).__geo_interface__),
        }
        for n, dt, g in districts
    ]
    union = unary_union(polys).buffer(0)
    outline = rnd(union.simplify(TOL_DISTRICTS, preserve_topology=True).__geo_interface__)
    world = Polygon([[-180, -85], [180, -85], [180, 85], [-180, 85], [-180, -85]])
    mask = rnd(world.difference(union.simplify(TOL_HOLE, preserve_topology=True)).__geo_interface__)

    OUT.mkdir(parents=True, exist_ok=True)

    def ts(name: str, obj: object, label: str) -> None:
        header = (
            f"/* {label} — Census 2011 boundaries (data.gov.in via india-geodata),\n"
            f"   generated by scripts/make_gujarat_geojson.py. Do not edit by hand. */\n"
            "// eslint-disable-next-line @typescript-eslint/no-explicit-any\n"
        )
        (OUT / f"{name}.ts").write_text(header + f"export const {name}: any = " + json.dumps(obj, separators=(",", ":")) + ";\n")

    ts("gujaratDistricts", {"type": "FeatureCollection", "features": feats}, "Gujarat district polygons")
    ts("gujaratOutline", {"type": "Feature", "properties": {"name": "GUJARAT"}, "geometry": outline}, "Gujarat state outline")
    ts("gujaratMask", {"type": "Feature", "properties": {}, "geometry": mask}, "Dark mask outside Gujarat")
    print(f"wrote {len(feats)} districts + outline + mask to {OUT}")


if __name__ == "__main__":
    main()
